### ISSUE TITLE
[Feature Request] Disable fade effect on titles that are shorter than maximum size of application name

### ISSUE THREAD

**Issue by kevlogan90** [lestcape/Global-AppMenu#10] opened 2015-06-02 17:31 UTC
If I open a program like firefox, the title shows the application name is firefox web, but the last couple of letters are faded out even though I have it set so the maximum size of the application name is 15 characters and firefox web is only 11 characters. I would like to have an option to have the fade effect enabled only on titles longer than the maximum size of the application length. Thanks!

**Comment by lestcape** [comment] 2015-06-03 00:11
The number of characters is an approximation, because not all have the same width. This is only true for monospace fonts. I sorry, but i don't agree with your idea. Let me explain you, because i wanna do what user want and i'm not a user (i don't like the global menu), so your request have more priority than what I think, but only if have sense and will be useful.

The faded out is not an esthetic way of cut a word. I do this because i want to separate the application name and the menu item name. To avoid user confusion, that will represent some seconds on the closing and opening. So, this is why i don't see the utility of this, is not esthetic as have a different looks and also could create confusion.

what is your point here?

**Comment by kevlogan90** [comment] 2015-06-03 03:14
I figured it was more aesthetic instead of using it to separate the application and menu. I couldn't think of another way beside making the application larger/bold font or a combination of both for titles that are longer than the max width. I would like to be able to see up to my set character limit. It isn't a big deal if this isn't a good way of doing it.

I think it would also be nice if there were two max width options one for if the menu is displayed and one if it isn't. So if there is no menu, then Firefox Web Browser could be displayed if I had 30 characters with no fade effect since this is less than the set limit, or have it fade out if it was set to something fewer like 15 characters,  and if the menu is displayed, then the current display would be used.

Thanks a lot for developing this applet. This has been a feature that I've been wanting for a long time.

**Comment by lestcape** [comment] 2015-06-03 13:38
Yes, but the problem is that. I can not force the cinnamon style to do what i want. I use the current style of applet label for application name and the current style of the popup submenu item for the menu. Is not my decision what colors or type of font will be apply. The theme authors can do that.

**Comment by kevlogan90** [comment] 2015-06-03 18:04
I understand your point. Would it be possible to do my second request? A second width option if the menu is not activated and there isn't a fade effect, or the fade effect only occurs if the title is longer than this length instead of always being present.

**Comment by lestcape** [comment] 2015-06-03 19:47
I will see if i can find a way to estimate better the picture size, because what you see as a text is not, is a picture, then have a width. The width of the picture are estimated by an approximation of the character width of the current font take on account the number of character that you want to see. So is not really easy, and i don't see that this will help really, because all application have a different name, so a different width and you can not guarantee that they will show on the current size of the picture.

**Comment by kevlogan90** [comment] 2015-06-03 21:22
So you are using the number of pixels to approximate, which is fine. I can use that to approximate the width of title that I want visible, but I think that if the menu is not being shown, then if the title image is not longer than the set number of pixels there shouldn't be a fade effect.

**Comment by lestcape** [comment] 2015-06-04 05:22
As i say, the approximation is an approximation, so i can not be sure if this happen or not. I can not be sure of the real size of the text, so i can not apply the comparison that you mention on the current state, because this will fail. What i can do is not compare anything, and replace the image with a text, but this have an inconvenient, they will be displayed different, because are not the same.

**Comment by kevlogan90** [comment] 2015-06-04 05:59
If that is the case, then the current behavior is fine. Functionality and consistency are more important, so this can be ignored.

**Comment by lestcape** [comment] 2015-06-04 06:49
I will try to find a way to estimate exactly the picture size, i don't promise any thing, because if i do this is because i don't find how, but thats not mean that is impossible. Just mean that i don't find it, maybe exist.

**Comment by kevlogan90** [comment] 2015-06-05 04:09
Thanks for giving it a try! This applet is really great!

**Comment by Meiden-fc** [comment] 2015-06-13 15:15
I agree with @kevlogan90

**Comment by d-belyakin** [comment] 2016-11-26 17:32
I think that some parts of code of "Window buttons with title" applet can be reused to achieve what @kevlogan90 want, ot it is also possible to use Global menu applet with combination of mentioned applet.
The main issue is that Window buttons with title shows window title, not application name

**Comment by lestcape** [comment] 2016-11-27 07:53
@d-belyakin thanks, but as i say, this is not a thing that i want to do, because i will need to remove the effect and the effect have a reason...

Anyway i will reuse the code of this applet, but not because i want to add this, what i want to add it' s the buttons. But not now, as i'm waiting for a resolution of this pull request, to know if i will add this or remove the applet:
https://github.com/linuxmint/Cinnamon/pull/5961

**Comment by d-belyakin** [comment] 2016-11-27 19:11
@lestcape am I understand correctly that this pull-request mimics Maximus extension behaviour on Muffin level? This is good approach.
What buttons did you mean? For close, maximize, minimize? If so, this is a good approach too. I also have such idea to implement buttons which behaves like in Unity (appearing by mouse hover), but I have a lack of time right now and poor JS expirience)

Many thanks for your answers!

**Comment by lestcape** [comment] 2016-11-27 20:41
Yes the pull mimics the Maximus extension at muffin level and yes, close, maximize, minimize buttons. The another option  like in Unity  will not be a thing that i want to do...

**Comment by lestcape** [comment] 2017-06-07 20:17
Not support for cinnamon anymore.

**Closed by lestcape** 2017-06-07 20:17 UTC
