### ISSUE TITLE
Update Manager issues

### ISSUE THREAD

**Issue by kevlogan90** [lestcape/Global-AppMenu#12] opened 2015-06-06 03:37 UTC
Selecting the Edit menu item in the update manager keeps adding a new line. Also, some of the text in the menus are not the same as when displayed in the update manager, so it says "_execute" instead of "Linux Kernels". Using cinnamon 2.6.7 and from the latest git source.

**Comment by lestcape** [comment] 2015-06-06 04:29
Your distro is mint? You say Mint update manager?

**Comment by lestcape** [comment] 2015-06-06 08:40
This is exactly what i don't want to do: https://github.com/linuxmint/mintupdate/pull/104
I can not fix all application that will not used an standar way on the menubar.

This is a Mint application and there are not problem, but see, i don't use Mint, so really i don't care.

**Comment by lestcape** [comment] 2015-06-07 02:44
The path was merged, so i will see if i can do something with the other problems.

**Comment by kevlogan90** [comment] 2015-06-07 17:24
Thanks

**Comment by lestcape** [comment] 2015-06-08 01:00
No matter, is difficult to realise the cause of any problem, as there are several things involved. Not all people are like mint devs, and if you say there are a problem in the code of someone, this someone became angry.

**Comment by kevlogan90** [comment] 2015-06-08 02:57
I feel like that's a one problem with open source. If you don't like it, then do it yourself, which then leads to a million different forks that all do the same task, but in slightly different ways.

**Comment by lestcape** [comment] 2015-06-08 03:47
You say something like this: https://github.com/linuxmint/Cinnamon/pull/4248 ? Thats is seriously, is affecting cinnamon from the source, to not mention the several project around this.

**Comment by kevlogan90** [comment] 2015-06-09 14:07
Yea. Making small fixes just adds to the mess, but it would be better if someone were able to fix the problem at the source, and not just modify cinnamon as a quick fix. If the quick fix needs to be done, then eventually I'm sure glib will be corrected and as Clem says, then the changes would have to be undone, but that just adds more work for cinnamon dev.

**Comment by lestcape** [comment] 2015-06-11 09:52
I can not fix this properly, the problem is that: They change the sensibility of the whole window, and this is a gtk2 app. So, the ubuntu patch only can capture the change in the sensitive property (enable/disable) of the menu items, and then the change is not reported in an event, but occurs. So, the only thing that i can do is close the menu when user try to access, and they are insensitive, and then user try to open the menu again try to read the sensitive state. I will try to find a better solution, but is complex.

**Comment by lestcape** [comment] 2015-06-11 16:39
Fixed in https://github.com/lestcape/Global-AppMenu/commit/940e89252f94604e23261bfc6111e8745b1133fd and https://github.com/linuxmint/mintupdate/pull/104

**Closed by lestcape** 2015-06-11 16:39 UTC
