### ISSUE TITLE
Menus with native GMenuModel is not shown

### ISSUE THREAD

**Issue by rilian-la-te** [lestcape/Global-AppMenu#5] opened 2015-05-01 15:42 UTC
I ran through all applications, and classify, which are not giving menus to your applet.
It is any application that export GMenuModel itself, not through unity-gtk-module.
I think, this issue can be caused by hardcoded path or something...

**Comment by rilian-la-te** [comment] 2015-05-02 06:04
About this bug: I have some question about implementation detail.

What is the reason of using one file and one class for DBusMenu and MenuModel? It is totally different...

**Comment by lestcape** [comment] 2015-05-02 06:07
Currently, I get the dbus menu path using the muffin values...

https://github.com/linuxmint/muffin/blob/master/src/core/window.c#L335
https://github.com/linuxmint/muffin/blob/master/src/core/window.c#L344
https://github.com/linuxmint/muffin/blob/master/src/core/window.c#L347

If muffin not have a path to me, i don' t have any thing, so if some one need a path is muffin, make this on javascript, will be slow and difficult i think.

I don't still use the appmenu, i only used the menubar path so my applet will not display the appmenu, also if i don't have a menubar path, how occurs on evince. In cinnamon i only have one thread (the compositor thread), and try to find all menu structure (also with icons), take a long time. Now this is slow and i don't want to be more slowly.

Maybe on the future if i found a way to reduce the performance impact.
Regards.

**Comment by rilian-la-te** [comment] 2015-05-02 06:09
This is not about AppMenu. file-roller and evince using MenuModel in their menubars also, and does not use _UNITY_GTK_ACTION_GROUP, AFAIK. This is a difference between native MenuModel apps and unity-gtk-module driven.

**Comment by lestcape** [comment] 2015-05-02 06:12
I have a unity (kde), menu model and a gtk menu model. They are different and i can not use the unity code to swap one into another (the indicator), so i get it directly from dbus.

**Comment by rilian-la-te** [comment] 2015-05-02 06:15
Do you use  _UNITY_GTK_ACTION_GROUP xprop anywhere?

**Comment by lestcape** [comment] 2015-05-02 06:24
What i do is something like this: https://github.com/RafaelBocquet/i3-hud-menu/blob/master/i3-hud-menu.py

Search if the register iface have a menu for me, and if not then try to find it on muffin...

**Comment by lestcape** [comment] 2015-05-02 06:30
I use the org.gtk.Actions dbus iface, so i never retrive directly the gtk action group, this occurs internally from the dbus iface. https://wiki.gnome.org/Projects/GLib/GApplication/DBusAPI

**Comment by lestcape** [comment] 2015-05-02 06:46
Can you give me some applications names that are not currently supported and they are supported on your xfce implementation, of course?

**Comment by rilian-la-te** [comment] 2015-05-02 08:39
Evince, file-roller, at least. Gnome-terminal is not supported by both, because it blacklisted in its source.

**Comment by lestcape** [comment] 2015-05-02 09:30
FlieRoller:
![captura de pantalla de 2015-05-02 04 22 24](https://cloud.githubusercontent.com/assets/1389572/7440587/dc577bdc-f083-11e4-9213-a8600ae7694f.png)

What your extension show is not the menubar, so evince is not an example...

**Comment by lestcape** [comment] 2015-05-02 10:51
Gnome terminal:
![captura de pantalla de 2015-05-02 05 10 50](https://cloud.githubusercontent.com/assets/1389572/7440785/d5ca735e-f08e-11e4-9b32-2cf3407e8e77.png)

I can path the extension to show the appmenu if the menubar is not pressent, without lost performance, and maybe i will do that, but is more important to me fix all bugs right now. I have a lot of bugs....

**Comment by lestcape** [comment] 2015-05-02 13:11
You are developing a thing for Arch. On Arch, they consider unity-gtk-module unusable out of the unity desktop. Thats is not true at all. What can not be used is the specific application patch (as the evince one). The applet is development to used with all ubuntu source and not with any other alternative implementation. If the alternative implementation not do the same as ubuntu do. If you want to support on Arch all applications that can be supported on ubuntu, to be used with this applet, you need to do all of ubuntu do on your alternative version for Arch, otherwise ofcourse this can not work. 

What you are considere a problem, is internally resolved by the ubuntu sourse and i don't care how... What i only do in the applet is show the result of that, i don't need to patch anything and i do not want to patch anything on javascript, because i have not a low level code to access the low level api and because this will be really slowly if i try to do that.

**Comment by lestcape** [comment] 2015-05-02 13:35
To help a little, i suppose that what happens is that ubuntu read the not standar model and then reported the menu as an standar one (exported the menu model), then i can read what they report on the applet and show it. If i will want to support evince then i  need to create a gtk module, to read the evince ui menu file, and then exported the menu using the standar gtk way or as the register one, but do that on javascript, will not be never a good solution.

**Comment by rilian-la-te** [comment] 2015-05-02 15:11
Yes, gnome-terminal is working on Ubuntu (but not in Arch)

**Comment by rilian-la-te** [comment] 2015-05-02 15:24
Evince exports (on 15.04):
```
_GTK_MENUBAR_OBJECT_PATH(UTF8_STRING) = "/org/gtk/Application/anonymous/menus/menubar"
_GTK_WINDOW_OBJECT_PATH(UTF8_STRING) = "/org/gtk/Application/anonymous/window/1"
_GTK_APPLICATION_OBJECT_PATH(UTF8_STRING) = "/org/gtk/Application/anonymous"
_UNITY_OBJECT_PATH(UTF8_STRING) = "/com/canonical/unity/gtk/window/0"
_GTK_UNIQUE_BUS_NAME(UTF8_STRING) = ":1.91"
```
And uses standard behaviour of Gtk3 MenuModel applications. I do not guess, why it is not working with your applet

**Comment by rilian-la-te** [comment] 2015-05-02 15:26
Evince only using non-standard object path of menubar object and action object, but same proto.

**Comment by lestcape** [comment] 2015-05-03 04:39
I have ubuntu 14.04, so i don't know what occurs on 15.04, i have also an unecessary backup way to get the menu model if muffin fail, https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/indicatorAppMenuWatcher.js#L527

So i don't know why then i can not read the evince menu... I will go to 15.04 to test what happen, then...

Thats good that you understand that what i do is just read things and then show it on cinnamon, sorry. If you have a way to get the menu model easy without hard code or you want that i support any of what you are making, i will do it, if what i need to do is not hard for javascript.

Thanks.

**Comment by lestcape** [comment] 2015-05-12 07:09
I'm reading the evince menu model, but not the actions...

**Comment by rilian-la-te** [comment] 2015-05-12 07:27
Can you show me your actions reading code? I cannot find it:-(

**Comment by lestcape** [comment] 2015-05-12 07:39
For all gtk application, I use the same dbus path _GTK_MENUBAR_OBJECT_PATH and the same bus name, _GTK_UNIQUE_BUS_NAME for actions and for the menu model, all work except evince.

Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Not exist the iface «org.gtk.Actions» in the object path /org/gtk/Application/anonymous/menus/menubar

This occurs when i call https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/dbusMenu.js#L625

And error is here:
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/dbusMenu.js#L630

**Comment by lestcape** [comment] 2015-05-12 08:30
Well is not because there are not one, just is because there are a lot...
![captura de pantalla de 2015-05-12 03 17 44](https://cloud.githubusercontent.com/assets/1389572/7582764/68e08650-f856-11e4-82fb-81d2cf09bd2e.png)

![captura de pantalla de 2015-05-12 03 23 27](https://cloud.githubusercontent.com/assets/1389572/7582866/0b58d7b6-f857-11e4-8667-c0a40cc3981b.png)

But not where i try to found one, i don't know if this will need an specific patch for evince to search the action on other place or if this could be more general for similar applications or what...

**Comment by rilian-la-te** [comment] 2015-05-12 11:06
Only for evince, AFAIK. Or use atoms, but it is very slow.

**Comment by lestcape** [comment] 2015-05-12 12:15
No way... https://github.com/lestcape/Global-AppMenu/commit/9cd43a8ff55ec98e83793bdbf253190caa0f60bf

Regards.

**Comment by rilian-la-te** [comment] 2015-05-12 12:58
Does not working? What about atoms? Or meta_window_get_utf8_property?

**Comment by lestcape** [comment] 2015-05-12 14:04
Not, what i was doing was wrong... The problem is that the gtk actions are split on 3 dbus properties. One for the application actions, another for the windows action, and another for what unity include to fix any problem. So, as i tested some things only, then i suppose that I only tested unity actions, but Evince have windows and application actions. so right now i connected the applet to all dbus patch and then I merged the action id that all proxy will provide, and then I do the same that i was doing. The result is that all is working now, except firefox.

**Closed** 2015-05-31 14:08 UTC
