### ISSUE TITLE
Cinnamon?

### ISSUE THREAD

**Issue by viggy96** [lestcape/Global-AppMenu#50] opened 2017-06-06 15:19 UTC
I saw that this repo doesn't support Cinnamon anymore, but does anyone have any idea where the Cinnamon one is? The README says 'forked by Clement' but I don't see it under him. Is there any global menu for Cinnamon?

**Comment by lestcape** [comment] 2017-06-06 16:45
Clement fork all and i remove all from spices. Because i do not want to work in this conditions and because my name was set as the author of a thing, that i really can not controlled. They now will not used the author name, and i have not problem in that way that this will be included (as is not my problem any-more). So, i donate all code to cinnamon (https://github.com/linuxmint/cinnamon-spices-applets/issues/668#issuecomment-304355484), but just if they want to include it.

I think you need to open an issue on cinnamon-spices-applets: https://github.com/linuxmint/cinnamon-spices-applets

If that what you want, or you also can merged the applet at your name... It's not any more my problem.

**Closed** 2017-06-06 16:46 UTC

**Comment by lestcape** [comment] 2017-06-19 00:55
Is not like  @JosephMcc say here https://github.com/linuxmint/Cinnamon/issues/6629#issuecomment-309313444 . Here are the commit that remove the stuff form a Mint repository (so, Clement fork it):
https://github.com/linuxmint/cinnamon-spices-applets/commit/8da141389eef1a06390d196c43c0ee0d0fce28c2
https://github.com/linuxmint/cinnamon-spices-desklets/commit/47582e46548f2cd3c50d3c0efffd962f02b64837

You open your issue in the wrong place. They don't want a global menu as an official extension, so i tell you, your option was open your request in the applet-repository and not in the official repository.

Good look.

**Comment by JosephMcc** [comment] 2017-06-19 00:59
Apologies. I clarified my statement on the linked comment. We did fork them all but all of your stuff was removed.

**Comment by lestcape** [comment] 2017-06-19 01:05
Yes, @JosephMcc no matter and thaks. I donate all to cinnamon https://github.com/linuxmint/cinnamon-spices-applets/issues/668#issuecomment-304355484 Just i don't want to continue with it, but i don't want to delete it, because someone could want to do it... I recommended open an issue in spices applet then...

Regards.

**Comment by lestcape** [comment] 2017-06-19 03:22
@viggy96 the global menu is working for the gtk applications thanks to unity-gtk-modules. As this packages is part of the unity desktop (and is develop by canonical) it will drooped in the future and will only be maintenance for ubuntu 16.04. So, Whatever the developer, he will need also to maintenance the unity-gtk-modules package and probably more packages on the future.

To be honest, i think not one will want to do that. Less if it will be to then give the credit to someone else while are you who are making the job. So, my advice is: forget of the support inside cinnamon. Or go to desktop that included it by default, or where the author of the extension will be his own manager.

**Comment by kalinchernev** [comment] 2017-08-14 15:05
Seems the last few issues open in the repo were about this, which I end up now at.
Adding a simple link in the main readme will save time from people redirect, just an idea.

**Comment by lestcape** [comment] 2017-08-14 15:19
Yes, if this will be an active repository you will have the right, but is not active so, i think is not important anything then. Waverer... You can fork it and add all information you want in your side without a problem.

Regards.

**Comment by lestcape** [comment] 2017-09-09 05:26
https://github.com/linuxmint/cinnamon-spices-applets/issues/998

**Comment by peharri** [comment] 2018-03-25 16:00
Leaving aside Lestcape's (understandable) frustration, does anyone know _why_ this isn't working any more? Ubuntu 18.04 still contains Unity (and thus the dependencies) and it'd be nice to get it working again if there's an easy fix - the problem is presumably something changed in Cinnamon that's broken it. I'd be happy to fork it with the changes.

**Comment by neowiz73** [comment] 2018-03-25 16:28
it was changes that were made in CJS. afaik, on Arch you can get this to work fine by downgrading CJS to 3.2. if i remember correctly I think it was 3.4 that made this no longer work.

**Comment by lestcape** [comment] 2018-03-25 17:56
Yes, unity-gtk-module it's better now (not worse) thanks to the enforce of Mate Desktop... So, it's still alive... The problem then is localized in a drastically improve of CJS, that also break a lot of things ofcourse. The applet need this things, but  are missing. So, it need maintenance to be working again.

Certainly it's probably useful read that information if you have the plan of update the extension: 
https://wiki.gnome.org/Initiatives/Wayland/GnomeShell/GnomeShell4

Several people (most of then are ubuntu developers), have more drastically BIG changes in mind for Gnome-Shell, this could impact the whole ecosystem and made obsolete all this code at once. So, take this in consideration if you want invert time in a code that use the St library.

**Comment by peharri** [comment] 2018-03-25 18:28
OK, thanks. It clicked, the issue is just the newer CJS is somewhat stricter with the "let" keyword. I fixed the issues and that seems to be the only thing wrong - I now have it working on my Ubuntu 18.04 system! (Yay!)

I can post a diff to this thread, or I can just post a fork. If I fork it, is there anything you want me to do? (I know for instance it currently has the name globalAppMenu@lestscape when put in the applets directory - do you want me to keep that name or change it? You did all the work, I only fixed three or four really, really, minor issues, so it seems unfair not to credit you! But it sounds  like you don't want your name on any forks, which is also understandable!)

**Comment by lestcape** [comment] 2018-03-25 18:45
@peharri I don't care what you want to do with it... Is yours.... :) You can change the uuid or not, this not mean anything to me, you can add a reference me as the original author or not, i also don't care. The only thing that disturb me is if you published a modified version some where that people think is my account. How you have not access to any of my accounts, there are not problem... Mint have access to my spices account, that is the big difference and what really bothered me, because they could change my code and do it as if I was the one who modified it. Thats all.

**Comment by peharri** [comment] 2018-03-25 21:59
OK, I'll add a new repo in the next day or so, I'll post a link here. Thanks!

**Comment by peharri** [comment] 2018-04-08 14:11
Sorry! Hadn't gotten around to it as I'm somewhat busy. I did check the last few bug reports (unrelated to it not working at all on more recent Cinnamons) and wasn't able to reproduce the issues reported, so I'm hoping it's generally OK now, but I'll will post here with the repo shortly.

**Comment by sjk7** [comment] 2018-04-08 14:14
ok ,thanks. Look forward to it.

**Comment by nill-morais** [comment] 2018-06-02 09:42
@peharri 
I am hopeful that everything is going to be ok. is there any release date?
