### ISSUE TITLE
Not work for root privileges

### ISSUE THREAD

**Issue by kopipait** [lestcape/Global-AppMenu#8] opened 2015-05-25 13:49 UTC
Not work for application with root privileges like synaptic, gparted, `sudo gedit`,...
Nice applet anyway. I love it.
![screenshot from 2015-05-25 20 41 03](https://cloud.githubusercontent.com/assets/11684816/7798095/8e472e8e-031f-11e5-852c-fdcc6cc0caef.png)

**Comment by rilian-la-te** [comment] 2015-05-25 14:24
AFAIK, this is a GMenuModel limitation.

**Comment by lestcape** [comment] 2015-05-26 01:53
Closed, by the above explanation.

**Comment by lestcape** [comment] 2015-06-15 11:23
There are a way to provide a solution, that i currently try to development, but has his inconvenients. As i see also @Meiden-fc requested this and this will be a common request, i will try to explain the complexity and the "solution" that i propose.

Please see this thread if you want to know more information about this: https://bugs.launchpad.net/indicator-appmenu/+bug/592842

The problem is that: The applications expose the menu in the session where they are running, this mean that i only can read the menu in the session where the application is running. Applications with elevated privileges are running in a root(admin) session, this session is different of the user session of course. I can run an intermediate program in the root session and send the menu information to the user session to be read for the applet, but this have a problem.

The intermediate program, need to be executed with an elevated permission to see the root session. To do that i will need to implement a daemon, to start the intermediate program with elevated privileges(so to enable it, you will need to provide a password for install the daemon), when cinnamon start (without ask for a password). If i let the thing in this way, this will be a violation of user privileges, and is a door open to be attack by a hacker. The hacker can create a client (as the applet will be) of my service and then request an action for the application that are running with elevated privileges.

To avoid this, i can request a password the first time that user try to access to the service, this can avoid an attack, but is problematic provide two time the password. One for the application and another for the menu.

Maybe i can implement this with both options and user can decide if they want or not want take risk. This will not be the only one application in the world that allow scalability of privileges, but sure is not the properly way of do the things.

**Comment by oliveiraev** [comment] 2016-01-22 14:37
How about the approach taken by network-manager? At low level, disable network interfaces is a superuser-only privilege, but is simple and transparent to do on any well-configured desktop environment. Another example is shutting down the computer.

**Comment by lestcape** [comment] 2016-01-22 16:55
@oliveiraev yes, both things are done using a dbus connection to an application that run inside a daemon(the same "solution" that i comment), the problem here is that this actions are known, but not in the global menu, then you will to open a door to all action of all application. In a generic application, you can have all possible actions, then you are opening a way to realize all this actions (with root privileges). This is the complexity, create a daemon like the network or power daemon is easy.

**Comment by canceralp** [comment] 2016-02-09 15:51
I could live with two passwords in every bootup. Would it be possible if root privileged apps look in their classical way with integrated app menus and all other apps use the global menu applet? 

PS: I have been trying out XFCE, MATE and Cinnamon for an alternative to Unity, but I wasn't ready to give up from global menus on the top bar. This applet of Cinnamon, has saved me from Unity. Thank you

**Comment by lestcape** [comment] 2016-02-25 22:00
@oliveiraev yes, i see your comment in the site of intelligent idea, but jayantana is not well implemented and have a lot of limitation, so probably i can not do anything. Anyway i can try.

Regards

**Comment by lestcape** [comment] 2016-02-25 22:25
@canceralp yes, your solution of use the non root privileged apps in their classical way  is the currently behaviour of unity, but i don't know how they do that. An alternative is black-list the root application manually for the root session. http://www.webupd8.org/2013/11/unity-global-menu-can-now-be-disabled.html

Pleasee see i say for root session, not your user. Execute the dconfig with sudo to allow access the root session.

The propertly way is create  an script  to not export the menu proxy, but i try to do that without a good result. Probably the good place for the script will be inside /etc/X11/Xsession.d

**Comment by canceralp** [comment] 2016-02-25 23:36
@lestcape unfortunately, the blacklisting makes no effect on root applications (tested on GParted, Software Center).

when used on a non-root app like Nemo, it works. 

Given the circumstences, the only way to reach menus on a root app is to disable the applet. This is definetely not hard to do when launching a root app but neither is the best looking way of having a global menu...

**Comment by lestcape** [comment] 2016-02-25 23:53
@canceralp :) i say execute dconfig **as root** you need to change the settings of the root session, not  your user session...

**Comment by canceralp** [comment] 2016-02-26 08:59
@lestcape I am guess, I am doing something wrong here. Just to make sure, my steps are;

open terminal and type "sudo dconf-editor" 
then head to the com-canonical-unity gtk module. 
then type ['gparted']  (I also tried ['sudo gparted'])
Then restart the computer

**Comment by lestcape** [comment] 2016-03-01 16:43
I do this sometime ago and was working. I will try to create a help with some steps.

**Comment by oliveiraev** [comment] 2016-03-02 15:18
> @oliveiraev yes, i see your comment in the site of intelligent idea, but jayantana is not well implemented and have a lot of limitation, so probably i can not do anything. Anyway i can try.
> 
> Regards

thank you for the attention!!

The extension is purely Javascript, doesn't? I can give it a look if I have some free time. But wont promise anything.

**Comment by lestcape** [comment] 2016-03-04 13:33
That's good, and yes is a pure javascript and also i think if the menu is working ok in ubuntu, also will work ok after a restart at less. There are something wrong with how the menu is reading probably or other things happened that i don't take on account. Sometime the menu is displayed ok, sometimes not.

**Comment by stunito0o0o0** [comment] 2016-12-03 14:18
So as far as I understood it is hard to make it work under root privileges, but can I make it stop hiding the original menu when I am working under root privileges? That way i can still use the ugly original menu, when root, and the global one when not root. I can do this manually now by disabling the applet while I finish whatever I am doing under root, and then enabling it again, but it is kind of annoying to do that  everytime I need to open synaptic or whatever.
Thanks.

**Comment by lestcape** [comment] 2016-12-03 19:45
@stunito0o0o0 you understand correctly (just not it's difficult, only insecure or impossible is will required to be secure), you will open a door to anyone. You need to do this procedure manually, because this is an applet, and then not required root privileges and not need to be installed like a packages, what is required to do will need to be done as root, so if i will do that i will need to create an additional task for this as root. also i don't know how do that in a general way like occurs in unity.

**Comment by stunito0o0o0** [comment] 2016-12-04 11:47
Okay, so is there some kind of a workaround, where the applet can detect a window with root privileges and show the original menu?
Thanks.

**Comment by lestcape** [comment] 2016-12-04 12:29
@stunito0o0o0 i will create a setting module to configure properly this task... I found how and i working on this....

Basically will be create a file /etc/profile.d/cinnamon-globalmenu.sh with this content:
```
if [ "$DESKTOP_SESSION" = "cinnamon" ] && [ -z "$UBUNTU_MENUPROXY" ]; then
   UBUNTU_MENUPROXY=0
   export "UBUNTU_MENUPROXY=$UBUNTU_MENUPROXY"
fi
```
Then add this lines to the end of the file .profile:
```
if [ "$DESKTOP_SESSION" = "cinnamon" ] && [ "$UBUNTU_MENUPROXY" = 0 ]; then
   UBUNTU_MENUPROXY=1
   export "UBUNTU_MENUPROXY=$UBUNTU_MENUPROXY"
fi
```
logout and login...

**Comment by stunito0o0o0** [comment] 2016-12-04 20:45
Thank you for your help and patience. I tried to follow your steps, but I kinda got lost (newbie here). As far as I understood, you will bring this option to the menu in the next update?

**Comment by stunito0o0o0** [comment] 2016-12-05 12:19
Okay so I created cinnamon-globalmenu.sh in that directory, but I don't understand where the .profile file is, so I can add the second code at the end of it.

**Comment by lestcape** [comment] 2016-12-05 17:50
This is just an idea, as i say i will provide an option to be done automatically, but this will required some things, that i have not implemented yet. I make some test and apparently create the file in that location don't work for some procedures, and work for other’s and it' s better use the file /etc/environment to declared the UBUNTU_MENUPROXY environment variable with 0 value and then use the ~/.profile file to set it to 1.

**Comment by lestcape** [comment] 2016-12-11 09:58
I add an option to set the environment variable, but please see. This is an extension on java script, i don't have a c code. So, i can not create a pam module and i can not override the cinnamon-session pam module. So, this is statically set in /etc/environment and /etc/profile.d/cinnamon-globalmenu.sh, this could have side effects on other desktop session like unity, this also can not work on some system that not derivate from debian if they don' t use pam or not set the environment file in the same location or also if they don' t call the script inside /etc/profile.d/.

The action will only take effect after logout and login. The result will be similar to unity, where root application do not hide the internal window menu.

This option ofcourse don' t solve the problem for root applications (as also it' s not solved in unity), just make the things more easy. 

https://github.com/lestcape/Global-AppMenu/commit/7b3b65f5a33cc69924f5f043f91b19b554f1ca07

**Comment by stunito0o0o0** [comment] 2016-12-17 16:40
Hello, sorry for the slow response, it  was a busy week. I tried the new version of the appmenu. First I want to apologise for my ignorance, but I don't fully understand the explanation you provided. What i did understand, to put it simply, the option added in the settings for the proxy evniroment variable is to turn the original menus on and the applet off, if selected, but only works after a logoff, correct? 
If so this is a step ahead i guess, but yes it doesn't solve the problem with the root applicatons.

P.S. Not sure if this is  a bug or it's because a did something, but when i switched the applet with the new version from github(and deleted the old config in ~/.cinnamon/configs/) the configure option says "cannot execute child process "xlet-settings" (no such file or directory)" when i click it from the RMB button menu of the applet, but when i open the "add applets to panel" and click the config menu applet form there it works fine and the settings open noramaly.

**Comment by lestcape** [comment] 2016-12-17 17:23
@stunito0o0o0 you are right about the bug, but don't about the source: https://github.com/linuxmint/Cinnamon/issues/6086

**"What i did understand, to put it simply, the option added in the settings for the proxy evniroment variable is to turn the original menus on and the applet off, if selected, but only works after a logoff, correct?"** Yes...

But you need to know that the patch (the option in the settings) will have side effect in other session if you have more than one session in your computer (for example unity + cinnamon) or (xfce + cinnamon) and also could not work, depending of the linux distro that you use, but will work for most commons distributions.

I hope

**Comment by lestcape** [comment] 2017-06-07 20:18
Not support for cinnamon any-more.

**Closed by lestcape** 2017-06-07 20:18 UTC
